parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $uploadPath: '%kernel.project_dir%/public/upload'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
